#=
pipeline.jl - SFC Asset Pipeline
Responsible for extracting Vue logic/templates from .sk files and 
generating corresponding TypeScript assets for the Vite frontend.
=#

using JSON

"""
    export_assets(input_path::String, output_dir::String)

Extracts Vue logic and templates from an .sk file, performs Julia interpolation,
and writes them to the specified output directory as TypeScript files.
"""
function export_assets(input_path::String, output_dir::String)
    isfile(input_path) || error("SakuraEngine [Pipeline] : Input file not found `$input_path`")
    mkpath(output_dir)

    content = read(input_path, String)
    script_code, template_code = extract_blocks(content)
    mod = eval_script(script_code)

    # 1. Export Vue Template (vue-template.ts)
    # We render Julia interpolations so they are static in the Vue template
    vue_template = replace(template_code, r"\{\{\|\|\s*(.*?)\s*\|\|\}\}"s => m -> begin
        expr_str = strip(m[6:end-5])
        val = Core.eval(mod, Meta.parse(expr_str))
        return string(val)
    end)
    
    # Strip sk-* directives from the Vue template
    vue_template = replace(vue_template, r"sk-[\w:-]+=\"(.*?)\"" => "")

    # Escape backticks and dollar signs for JS template string
    safe_vue_template = replace(vue_template, "`" => "\\`")
    safe_vue_template = replace(safe_vue_template, "\$" => "\\\$")
    
    template_path = joinpath(output_dir, "vue-template.ts")
    write(template_path, "export default `$(safe_vue_template)`")

    # 2. Export Vue Logic (generated-logic.ts)
    script_re = r"<script type=\"sk-ts\">(.*?)</script>"s
    script_match = match(script_re, content)
    user_js = script_match !== nothing ? script_match.captures[1] : "// No logic found"

    # Interpolate Julia values into JS with JSON encoding
    user_js = replace(user_js, r"\{\{\|\|\s*(.*?)\s*\|\|\}\}"s => m -> begin
        expr_str = strip(m[6:end-5])
        val = Core.eval(mod, Meta.parse(expr_str))
        return JSON.json(val)
    end)

    logic_ts = """
    /**
    * Generated by SakuraEngine. Do not edit manually.
    */
    import { ref, computed, onMounted, reactive, watch } from 'vue'

    export default function setupUserLogic() {
    $(user_js)
    }
    """
    logic_path = joinpath(output_dir, "generated-logic.ts")
    write(logic_path, logic_ts)

    return true
end

"""
    init_frontend(project_path::String)

Initializes a Vite + Vue project for SakuraEngine by creating the necessary 
bridge files in `src/sakura/`.
"""
function init_frontend(project_path::String)
    sakura_dir = joinpath(project_path, "src", "sakura")
    mkpath(sakura_dir)

    # Boilerplate 1 : app.ts
    app_ts = """
    import { createSSRApp } from 'vue'
    import template from './vue-template'
    import setupUserLogic from './generated-logic'

    export function createSkPanelApp() {
      return createSSRApp({
        template: template,
        setup() {
          const userVariables = setupUserLogic()
          return typeof userVariables === 'object' ? { ...userVariables } : {}
        },
      })
    }
    """

    # Boilerplate 2 : entry-client.ts
    client_ts = """
    import { createSkPanelApp } from './app'

    const mountNode = document.getElementById('sk-hydration-area')

    if (mountNode) {
      createSkPanelApp().mount(mountNode)
    }
    """

    # Boilerplate 3 : entry-server.ts
    server_ts = """
    import { renderToString } from '@vue/server-renderer'
    import { createSkPanelApp } from './app'

    export async function renderVuePanel() {
      const app = createSkPanelApp()
      return await renderToString(app)
    }
    """

    write(joinpath(sakura_dir, "app.ts"), app_ts)
    write(joinpath(sakura_dir, "entry-client.ts"), client_ts)
    write(joinpath(sakura_dir, "entry-server.ts"), server_ts)

    # Boilerplate 4 : scripts/render-vue-panel.ts ( for Julia to call )
    render_script_dir = joinpath(project_path, "scripts")
    mkpath(render_script_dir)
    
    node_render_ts = """
    import { writeFileSync } from 'node:fs'
    import { renderVuePanel } from '../src/sakura/entry-server'

    const args = process.argv.slice(2)
    const outFlagIndex = args.indexOf('--out')
    const outPath = outFlagIndex !== -1 && outFlagIndex < args.length - 1 ? args[outFlagIndex + 1] : null

    const html = await renderVuePanel()

    if (outPath) {
      writeFileSync(outPath, html)
    } else {
      process.stdout.write(html)
    }
    """
    write(joinpath(render_script_dir, "render-vue-panel.ts"), node_render_ts)

    println("SakuraEngine [Pipeline] : Frontend initialized in `$(project_path)`")
    println("- Bridge files created in `src/sakura/`")
    println("- Node.js renderer created in `scripts/render-vue-panel.ts`")
    return true
end
