using SakuraEngine
using JSON

# Usage : julia --project=. scripts/render_hydration_example.jl

input_path = joinpath(@__DIR__, "..", "template_example", "hydration_example.sk")
workspace_dir = joinpath(@__DIR__, "..", "sakura-vue", ".sakura")
src_dir = joinpath(@__DIR__, "..", "sakura-vue", "src")
base_html_path = joinpath(workspace_dir, "hydration_example.base.html")
state_path = joinpath(workspace_dir, "vue-panel-state.json")
template_path = joinpath(workspace_dir, "vue-template.ts")
logic_path = joinpath(src_dir, "generated-logic.ts")
preview_output_path = joinpath(@__DIR__, "..", "sakura-vue", "index.html")

mkpath(workspace_dir)

content = read(input_path, String)
script, template = SakuraEngine.extract_blocks(content)
mod = SakuraEngine.eval_script(script)

# 1. Export Vue Template as a TS Module
# Instead of just replacing markers, we RENDER them so they are static in Vue
vue_template = replace(template, r"\{\{\|\|\s*(.*?)\s*\|\|\}\}"s => m -> begin
    expr_str = strip(m[6:end-5])
    val = Core.eval(mod, Meta.parse(expr_str))
    return string(val)
end)
vue_template = replace(vue_template, r"sk-[\w:-]+=\"(.*?)\"" => "")

# Escape backticks and dollar signs for JS template string
safe_vue_template = replace(vue_template, "`" => "\\`")
safe_vue_template = replace(safe_vue_template, "\$" => "\\\$")
write(template_path, "export default `$(safe_vue_template)`")

# 2. Export Vue Logic ( from <script type="sk-ts"> block )
script_re = r"<script type=\"sk-ts\">(.*?)</script>"s
script_match = match(script_re, content)
user_js = script_match !== nothing ? script_match.captures[1] : "// No logic found"

# Interpolate Julia values into JS with JSON encoding
user_js = replace(user_js, r"\{\{\|\|\s*(.*?)\s*\|\|\}\}"s => m -> begin
    expr_str = strip(m[6:end-5])
    val = Core.eval(mod, Meta.parse(expr_str))
    return JSON.json(val)
end)

logic_ts = """
/**
 * Generated by SakuraEngine. Do not edit manually.
 */
import { ref, computed, onMounted, reactive, watch } from 'vue'

export default function setupUserLogic() {
$(user_js)
}
"""
write(logic_path, logic_ts)

# 3. Render Final HTML for Server
html = SakuraEngine.render_file(input_path)
write(base_html_path, html)
write(preview_output_path, html)

println("Sakura-SFC Pipeline Finished.")
println("")
println("Next :")
println("1. cd sakura-vue")
println("2. npx tsx scripts/render-vue-panel.ts --out .sakura/vue-panel.ssr.html")
println("3. cd ..")
println("4. julia --project=. scripts/assemble_hydration_example.jl")
