<sk-script>
x = 10
name = "Sakura"

items = [1,2,3]
</sk-script>

<sk-template>
<div>
    <p>Hello {{ name }}</p>
    <p>{{ x + 5 }}</p>
</div>
<div>
    <p
      sk-if="x > 5"
    >
      big
    </p>
    <p
      sk-if="x < 5"
    >
      small
    </p>
</div>
<ul>
  <li
    sk-for="item in items"
  >
    <span
      sk-if="item > 1"
    >
        {{ item }}
    </span>
  </li>
</ul>
</sk-template>